sulu_media:
    storage: google_cloud
    storages:
        google_cloud:
            key_file_path: '%env(resolve:GOOGLE_STORAGE_KEY_FILE)%'
            bucket_name: '%env(resolve:GOOGLE_STORAGE_BUCKET_NAME)%'
