sulu_preview:
    cache_adapter: "cache.adapter.redis"

framework:
    cache:
        prefix_seed: eu.gcr.io/sulu-io/sulu
        default_redis_provider: "redis://%env(resolve:REDIS_PASSWORD)%@%env(resolve:REDIS_HOST)%/1"
